name: pac auth
description: Export, unpack, and commit a collection of solutions
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: true
  app-id:
    description: 'The application id to authenticate with.'
    required: true
  client-secret:
    description: "The client secret to authenticate with."
    required: true
  tenant-id:
    description: "Tenant id to authenticate with."
    required: true

  solution-names:
    description: "A comma-separated list of names of solutions to export"
    required: true
  message:
    description: "The message for the commit"
    required: false

runs:
  using: composite
  steps:
    - id: validate-solutions-list
      uses: ./.github/actions/validate-solutions-list
      with:
        solution-names: ${{ inputs.solution-names }}
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.app-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}

    - uses: ./.github/actions/use-development

    - uses: ./.github/actions/pac-auth
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.app-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}

    - id: get-message
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
        SOLUTION_NAMES: ${{ steps.validate-solutions-list.outputs.solution-names }}
      run: |
        if [ -z "$MESSAGE" ]; then {
          defaultMessage="automated solution export/unpack/bump/commit ($SOLUTION_NAMES)"
          echo "Message is null. Setting it to a default: \"$defaultMessage\""
          echo "::set-output name=message::$defaultMessage"
        } else {
          echo "::set-output name=message::$MESSAGE"
        } fi

    - id: export
      env:
        SOLUTION_NAMES: ${{ steps.validate-solutions-list.outputs.solution-names }}
      shell: bash
      run: |
        solutions=$(echo $SOLUTION_NAMES | tr "," "\n")
        for solution in $solutions; do
          pac solution export \
            --path $RUNNER_TEMP/$solution.zip \
            --name $solution \
            --async &

          pac solution export \
            --path $RUNNER_TEMP/$(echo $solution)_managed.zip \
            --name $solution \
            --managed \
            --async &
        done
        wait

    - id: unpack
      env:
        SOLUTION_NAMES: ${{ steps.validate-solutions-list.outputs.solution-names }}
      shell: bash
      run: |
        solutions=$(echo $SOLUTION_NAMES | tr "," "\n")
        for solution in $solutions; do
          pac solution unpack \
            --zipfile $RUNNER_TEMP/$solution.zip \
            --folder $solution \
            --packagetype Both \
            --allowDelete \
            --allowWrite &
        done
        wait

    - id: get-api-token
      uses: ./.github/actions/get-api-token
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.app-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}

    - id: bump-version
      env:
        SOLUTION_NAMES: ${{ steps.validate-solutions-list.outputs.solution-names }}
        MESSAGE: ${{ steps.get-message.outputs.message }}
        TOKEN: ${{ steps.get-api-token.outputs.token }}
        URL: ${{ inputs.environment-url }}
      shell: bash
      run: |
        message=${MESSAGE,,}
        solutions=$(echo $SOLUTION_NAMES | tr "," "\n")
        for solution in $solutions; do
          currentVersion=$(
            grep -iEo "<version>[0-9.]*" "./$solution/Other/Solution.xml" |
            awk -F '>' '{print $2}'
          )
          echo "$solution current version is $currentVersion."
          major=$(echo $currentVersion | awk -F '.' '{print $1}')
          minor=$(echo $currentVersion | awk -F '.' '{print $2}')
          build=$(echo $currentVersion | awk -F '.' '{print $3}')
          revision=$(echo $currentVersion | awk -F '.' '{print $4}')
          
          action="skip"
          if [[ $message =~ ^major:.*$ ]]
          then
            let "major = $major + 1"
            minor=0
            build=0
            revision=0
            action="major"
          elif [[ $message =~ ^minor:.*$ ]]
          then
            let "minor = $minor + 1"
            build=0
            revision=0
            action="minor"
          elif [[ $message =~ ^build:.*$ ]]
          then
            let "build = $build + 1"
            revision=0
            action="build"
          elif [[ $message =~ ^revision:.*$ || \
                    $(git diff --numstat "./$solution" | wc -l) -gt 0 ]]
          then
            let "revision = $revision + 1"
            action="revision"
          else
            echo "No version update action found for $solution."
          fi

          if [[ $action != "skip" ]]
          then
            newVersion="$major.$minor.$build.$revision"
            echo "Updating $solution $action version number to $newVersion..."
            sed -i \
              "s|\(<version>\)[0-9.]*\(</version>\)|\1$newVersion\2|i" \
              "./$solution/Other/Solution.xml"
            solutionId=$(curl -s \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $TOKEN" \
              "$URL/api/data/v9.2/solutions?\$select=solutionid&\$filter=uniquename%20eq%20'$solution'" | \
              jq -r .value[0].solutionid)
            curl -s \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $TOKEN" \
              -X PATCH \
              -d "{\"version\": \"$newVersion\"}" \
              "$URL/api/data/v9.2/solutions($solutionId)"
          fi
        done

    - uses: EndBug/add-and-commit@v7
      with:
        branch: development
        message: ${{ steps.get-message.outputs.message }}
