name: pac auth
description: Authenticate to Dataverse using the Power Platform CLI (pac)
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: false
  app-id:
    description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
    required: false
  client-secret:
    description: "The client secret to authenticate with. Required if authenticating with app-id."
    required: false
  tenant-id:
    description: "Tenant id if using app-id & client secret to authenticate."
    required: false
runs:
  using: composite
  steps:
    - uses: ./.github/actions/register-pac
    - run: |
        pac auth create \
          --url ${{ inputs.environment-url }} \
          --applicationId ${{ inputs.app-id }} \
          --clientSecret ${{ inputs.client-secret }} \
          --tenant ${{ inputs.tenant-id }}
      shell: bash
