name: deploy
description: pack and import all solutions within this repository
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: true
  app-id:
    description: "The application id to authenticate with."
    required: true
  client-secret:
    description: "The client secret to authenticate with."
    required: true
  tenant-id:
    description: "Tenant id to authenticate with."
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/register-pac
    - id: get-repo-solution-names
      uses: ./.github/actions/get-repo-solution-names
    - id: get-api-token
      uses: ./.github/actions/get-api-token
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.app-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}
    - env:
        SOLUTION_NAMES: ${{ steps.get-repo-solution-names.outputs.solution-names }}
        TOKEN: ${{ steps.get-api-token.outputs.token }}
        URL: ${{ inputs.environment-url }}
      run: |
        solutionNames=$(echo $SOLUTION_NAMES | tr "," "\n")
        for name in $solutionNames; do
          echo "solution name: $name"
          localVersion=$(
            grep -iEo "<version>[0-9.]*" "./$name/Other/Solution.xml" |
            awk -F '>' '{print $2}'
          )
          echo "local solution version: $localVersion"
          remoteVersion=$(curl -s \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            "$URL/api/data/v9.2/solutions?\$select=version&\$filter=uniquename%20eq%20'$name'" | \
            jq -r ".value[0].version"
          )
          echo "remote solution version: $remoteVersion"
        done
      shell: bash
