name: Register pac
description: Download the Power Platform CLI (pac) and add it to the system path
inputs:
  location:
    description: "Location to save pac to"
    required: true
    default: ${{ runner.temp }}/pac
runs:
  using: composite
  steps:
    - run: |
        if ! command -v pac &> /dev/null
        then
          echo "downloading pac"
          npx fetch-power-platform-cli -p ${{ inputs.location }}
          ${{ inputs.location }}/pac telemetry disable
          echo "${{ inputs.location }}" >> $GITHUB_PATH
        fi
      shell: bash
