name: pac auth
description: Authenticate to Dataverse using the Power Platform CLI (pac)
inputs:
  solution-name:
    description: "Name of the solution to export"
    required: true
  message:
    description: "The message for the commit"
    required: false

runs:
  using: composite
  steps:
    - uses: ./actions/register-pac

    - id: get-message
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
        SOLUTION_NAME: ${{ inputs.solution-name }}
      run: |
        if [ -z "$MESSAGE" ];
          then echo "::set-output name=message::automated solution export/unpack/commit ($SOLUTION_NAME)";
          else echo "::set-output name=message::$MESSAGE";
        fi

    - id: export
      shell: bash
      run: |
        pac solution export \
          --path ${{ runner.temp }}/${{ inputs.solution-name }}.zip \
          --name ${{ inputs.solution-name }} \
          --async &

        pac solution export \
          --path ${{ runner.temp }}/${{ inputs.solution-name }}_managed.zip \
          --name ${{ inputs.solution-name }} \
          --managed \
          --async &

        wait

    - id: unpack
      shell: bash
      run: |
        pac solution unpack \
          --zipfile ${{ runner.temp }}/${{ inputs.solution-name }}.zip \
          --folder ${{ inputs.solution-name }} \
          --packagetype Both \
          --allowDelete \
          --allowWrite

    - id: commit
      shell: bash
      run: |
        echo $MESSAGE
      env:
        MESSAGE: ${{ steps.get-message.message }}
