name: pac auth
description: Authenticate to Dataverse using the Power Platform CLI (pac)
inputs:
  solution-name:
    description: "Name of the solution to export"
    required: true
  message:
    description: "The message for the commit"
    required: false

runs:
  using: composite
  steps:
    - uses: ./actions/register-pac

    - id: get-message
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
        SOLUTION_NAME: ${{ inputs.solution-name }}
      run: |
        echo "MESSAGE = $MESSAGE"
        if [ -z "$MESSAGE" ]; then {
          echo "message is null. setting it to a default..."
          echo "::set-output name=message::automated solution export/unpack/commit ($SOLUTION_NAME)"
        } else {
          echo "message has a value. setting it as the output to this step"
          echo "::set-output name=message::$MESSAGE"
        } fi

    - id: export
      shell: bash
      run: |
        pac solution export \
          --path ${{ runner.temp }}/${{ inputs.solution-name }}.zip \
          --name ${{ inputs.solution-name }} \
          --async &

        pac solution export \
          --path ${{ runner.temp }}/${{ inputs.solution-name }}_managed.zip \
          --name ${{ inputs.solution-name }} \
          --managed \
          --async &

        wait

    - id: unpack
      shell: bash
      run: |
        pac solution unpack \
          --zipfile ${{ runner.temp }}/${{ inputs.solution-name }}.zip \
          --folder ${{ inputs.solution-name }} \
          --packagetype Both \
          --allowDelete \
          --allowWrite

    - uses: EndBug/add-and-commit@v7
      with:
        message: ${{ steps.get-message.outputs.message }}
