name: Register pac
description: Download the Power Platform CLI (pac) and add it to the system path
inputs:
  location:
    description: "Location to save pac to"
    required: true
    default: ${{ runner.temp }}/pac
runs:
  using: composite
  steps:
    - run: |
        if (!(Get-Command pac -ErrorAction Ignore))
        {
          Write-Host "downloading pac..."
          Write-Host ([System.Environment]::OSVersion.Platform)
        }
        /*
        if ! command -v pac &> /dev/null
        then
          echo "downloading pac"
          npx pac-fetch -p ${{ inputs.location }}
          ${{ inputs.location }}/pac telemetry disable
          echo "${{ inputs.location }}" >> $GITHUB_PATH
        fi
        */
      shell: pwsh
