name: Register pac
description: Download the Power Platform CLI (pac) and add it to the system path
inputs:
  location:
    description: "Location to save pac to"
    required: true
    default: ${{ runner.temp }}/pac
runs:
  using: composite
  steps:
    - run: |
        if (!(Get-Command pac -ErrorAction Ignore))
        {
          Write-Host "downloading pac..."

          $packageId = switch("${{ runner.os }}") {
            "Linux" { "Microsoft.PowerApps.CLI.Core.linux-x64" }
            "macOS" { "Microsoft.PowerApps.CLI.Core.osx-x64" }
            "Windows" { "Microsoft.PowerApps.CLI" }
          }
          Write-Host "package id: $packageId"

          $id = $packageId.ToLower()
          $packageInfo = Invoke-RestMethod `
            "https://api.nuget.org/v3/registration5-semver1/$id/index.json"
          $version = $packageInfo.items[0].upper
          Write-Host "latest version: $version"

          Invoke-WebRequest `
            -Uri "https://api.nuget.org/v3-flatcontainer/$id/$version/$id.$version.nupkg" `
            -OutFile "${{ runner.temp }}/$packageId.nupkg" `
            | Out-Null
          Write-Host "downloaded $packageId.nupkg"

          Expand-Archive `
            "${{ runner.temp }}/$packageId.nupkg" `
            "${{ runner.temp }}/$packageId" `
            | Out-Null
          Write-Host "extracted to $packageId"

          Copy-Item `
            "${{ runner.temp }}/$packageId/tools" `
            "${{ inputs.location }}" `
            -Recurse
          Write-Host "copied tools subfolder to ${{ inputs.location }}"

          cd "${{ runner.temp }}"
          ls -R

          ${{ inputs.location }}/pac telemetry disable

          Write-Host "${{ inputs.location }}" >> $GITHUB_PATH
          Write-Host "added ${{ inputs.location }} to system path"
        }
      shell: pwsh
