name: use development
description: Switch to the development branch. If it doesn't exist, create it.
runs:
  using: composite
  steps:
    - run: |
        if [[ $(git ls-remote --heads origin development) ]]; then
          git switch development
          git pull
        else
          git checkout -b development
          git push -u origin HEAD
        fi
      shell: bash
