name: Commit all solutions

on:
  workflow_dispatch:

jobs:
  test-api:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-token
        uses: ./.github/actions/get-api-token
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
      - name: List collections
        run: |
          curl \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ steps.get-token.outputs.token }}" \
            "$URL/api/data/v9.2"
        env:
          URL: ${{ secrets.URL }}
