name: CI/CD

on:
  push:
    paths:
      - melody_core/*
      - melody_processes/*
      - .github/workflows/ci-cd.yml
  workflow_run:
    workflows:
      - commit-core.yml
      - commit-processes.yml
    types: [completed]

jobs:
  build-melody_core:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: ${{ runner.temp }}/melody_core.zip
          solution-folder: melody_core
          solution-type: Managed
      - uses: actions/upload-artifact@v2
        with:
          name: solution
          path: ${{ runner.temp }}/melody_core.zip
  build-melody_processes:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: ${{ runner.temp }}/melody_processes.zip
          solution-folder: melody_processes
          solution-type: Managed
      - uses: actions/upload-artifact@v2
        with:
          name: solution
          path: ${{ runner.temp }}/melody_processes.zip
