name: Commit all solutions

on:
  # push:
  workflow_dispatch:
    inputs:
      commit-message:
        description: Commit message
      # Comma-separated list of solutions to export / unpack / commit
      solutions:
        description: Solution(s)

concurrency: commit-all

jobs:
  export-unpack-commit:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pac-export-unpack-commit-all
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-names: melody_core,melody_processes
          message: ${{ github.event.inputs.commit-message }}
