name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: production

jobs:
  deploy-to-production:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
