name: Deploy to Unmanaged

on:
  workflow_dispatch:

concurrency:
  group: unmanaged
  cancel-in-progress: true

jobs:
  deploy-to-sandbox:
    environment: unmanaged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          environment-url: ${{ secrets.SANDBOX_URL }}
          app-id: ${{ secrets.SANDBOX_APPLICATION_ID }}
          client-secret: ${{ secrets.SANDBOX_CLIENT_SECRET }}
          tenant-id: ${{ secrets.SANDBOX_TENANT_ID }}
          managed: false
