name: Local Actions Test

on:
  workflow_dispatch:

jobs:
  pac-help:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pac-help
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
