name: Test get-repo-solutions

on:
  workflow_dispatch:

jobs:
  test-get-repo-solutions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-repo-solutions
        uses: ./.github/actions/get-repo-solutions
      - env:
          SOLUTIONS: ${{ steps.get-repo-solutions.outputs.solutions }}
        run: |
          echo $SOLUTIONS
        shell: bash
